apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apiKey: AgASj4fsnURN2CWGBMre+pczEjpHSZGfhKNka7Wta/0+CdDehRxp0dVhf8pX6OrKhHf1y8BXxXgRyAR0PcXgaCLhG6mxqyKnpMoUG02j/4AFEwcEAxg010YdsVXzVwQ7tFQYfBvUsvip9ogIc3UUofh7ah/t26sOq+2ysvfujTMFWc8GQ89nh8Z2xoqP81D0vdXiKQaB3x0qHBC6V+V91ey727fFtuH9/Ik2+kZZ0ULU9K/OnG+zZa51708JgnaJNOkHKo14zMxJFstVvkQ3e//M/O2cFgTPDryGASy5Sk0Two73KziSobZ2FHYEriCMth7fnOKkKEdg/KLXTDfe4pUrq+JOYGsin297ULNvSf+MM1grPbQLQxgbpRDz4avQ9yEqki4N+44vjF/cE8Fx2KbA64pYdYZvX2+BTTe99/qvjG15Qmvh2zSaXVJb6yTrsgWqIfsl6QUBaXQyLu1xMGCIGtGQvjUXJLl1C/soYfCqxYbIaRYy42v1Wvu46zLZpzCudRhYsEkuVJYEzVOpCedaD65e2tXD0bfFeI7F0RYtdCCg4CU1k6zH0aIAGc3aJ2SSDon48E5SJDpnUDdIMwdcgTCPEk4/ng9empgT12BqUeUN8LnU3+m/F/Fx0Ojby/1pjMSmbQBzSqo6Nt23sP+aRp/DMNF3YQJvfqA+vRuqeOTsqYjgQacdFaP/VNawg3D3Ib0dA1GlxeU2x/ANCKBzUB9uriO59WJjOYh71f5DZ3fvXc6pwm4=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque

