apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rarquevaux/SampleGitOpsApp.git
    path: mychart
    targetRevision: main
    helm:
      releaseName: nginx
      values: |
        replicaCount: 2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
